# @package _global_
defaults:
  - _self_
  - env: ant
  - policy: default
  - agent: sb3_ppo
  - learner: sb3_learner
  - callbacks: default
  - hparams_search: null
  - experiment: null

seed: 1234

task_name: "train_${env.id}_default"
log_dir: ./logs

run_id: ${task_name}/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${log_dir}/runs/${run_id}
  sweep:
    dir: ${log_dir}/multiruns/${run_id}
    subdir: ${hydra.job.num}

checkpoint_path: ${hydra:runtime.output_dir}/checkpoints
tensorboard_path: ${hydra:runtime.output_dir}/tensorboard

