defaults:
  - default

id: CrippledAnt
version: v5

register:
    entry_point: src.envs.ant:${env.id}

train_env:
  _target_: ${env.vec_env}
  env_id: ${env.env_id}
  n_envs: 4
  env_kwargs:
    injury: little
    
  vec_env_cls: ${env.vec_env_cls}
  seed: ${seed}

eval_env:
  _target_: ${env.vec_env}
  env_id: ${env.env_id}
  n_envs: 5
  env_kwargs: ${env.train_env.env_kwargs}
  vec_env_cls: ${env.vec_env_cls}
  seed: ${seed}

